name: Build

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle Cache
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache
      - name: Cache Gradle Wrapper
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run build
        run: |

      - uses: codecov/codecov-action@v2
        with:
          directory: ./build/jacoco
          verbose: true # optional (default = false)